### ISSUE TITLE
change density in contextual menu

### ISSUE THREAD

**Issue by ozeta** [dannycolin/ff-ultra-compact-mode#1]
Is it possible to change the density in the contextual menu (the one triggered by mouse right click)?

**Comment by dannycolin** [comment]
> Is it possible to change the density in the contextual menu (the one triggered by mouse right click)?

Are you on Windows?

**Comment by ozeta** [comment]
yes, win10

**Comment by sagars007** [comment]
> 
> 
> Is it possible to change the density in the contextual menu (the one triggered by mouse right click)?

You can add this code for context menu compact density:

https://gist.github.com/sagars007/e8cc9d7276443ea51a622acbb78d6c64
